### ISSUE TITLE
Kitchen failures: 84e603ec26eaff142b36ad4610a0c702898f7dd3

### ISSUE THREAD

**Issue by ianmiell** [IshentRas/cookbook-openshift3#131] opened 2017-05-23 05:20 UTC
@jperville @IshentRas 

Kitchen failure on:

http://jenkins.meirionconsulting.tk/job/cookbook-openshift3/job/master/31/consoleFull

kitchen converge standalone-ose15-centos-72 PASS
kitchen converge cluster-native-ose15-centos-72 FAIL

Failures on:

  Service origin-master-api
     ✔  should be installed[0m
     ∅  should be enabled
     expected that `Service origin-master-api` is enabled[0m
     ✔  should be running[0m
  Service origin-master-controllers
     ✔  should be installed[0m
     ∅  should be enabled
     expected that `Service origin-master-controllers` is enabled[0m

**Comment by jperville** [comment] 2017-05-23 06:58
Hello @ianmiell , this seems to be a recent regression on https://github.com/IshentRas/cookbook-openshift3/commit/9defee8f9433833825b9c3d8c6dc8f7cc9dc533f#diff-e7b2f8bfaaedd6b2aa15af4315c1fdc4 (look for `:enable` in the diff). Will work on a quick PR.

**Comment by jperville** [comment] 2017-05-23 07:41
Should be fixed in #132.

**Closed** 2017-05-23 20:17 UTC
Labels: bug
