### ISSUE TITLE
No such file or directory @ rb_sysopen - /etc/origin/master/openshift-registry.crt

### ISSUE THREAD

**Issue by ebenezar-mccoy** [IshentRas/cookbook-openshift3#122] opened 2017-05-17 07:36 UTC
Hi,

During fresh installation i'm struggling with the follow error:

    Errno::ENOENT
    -------------
    No such file or directory @ rb_sysopen - /etc/origin/master/openshift-registry.crt

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/cookbook-openshift3/recipes/master_cluster.rb

    165:       remote_file "#{node['cookbook-openshift3']['master_generated_certs_dir']}/openshift-#{peer_server['fqdn']}/#{master_certificate}" do
    166:         source "file://#{node['cookbook-openshift3']['openshift_master_config_dir']}/#{master_certificate}"
    167:       end
    168:     end

I'm unable find part that is reponsible for generating "file:///etc/origin/master/openshift-registry.crt"

I am trying to deploy minimal native cluster configuration by example provided in readme file.

my configuration:

```
"override_attributes": {
    "cookbook-openshift3": {
      "openshift_deployment_type": "origin",
      "ose_major_version": "1.5",
      "ose_version": "1.5.0-1.el7",
      "openshift_common_portal_net": "172.30.0.0/16",
      "openshift_master_sdn_cluster_network_cidr": "10.128.0.0/14",
      "openshift_hosted_metrics_parameters": {
        "IMAGE_VERSION": "v1.5.0"
      },
      "openshift_HA": true,
      "openshift_cluster_name": "oso.some.domain.net",
      "persistent_storage": [
        {
          "name": "registry",
          "capacity": "5Gi",
          "access_modes": "ReadWriteMany",
          "server": "osc.some.domain.net",
          "path": "/opt/nfs/registry",
          "claim": {
            "namespace": "default"
          }
        },
        {
          "name": "metrics",
          "capacity": "3Gi",
          "access_modes": "ReadWriteOnce",
          "server": "osc.some.domain.net",
          "path": "/opt/nfs/metrics",
          "policy": "Recycle"
        },
        {
          "name": "logging",
          "capacity": "2Gi",
          "access_modes": "ReadWriteOnce",
          "server": "osc.some.domain.net",
          "path": "/opt/nfs/logging",
          "policy": "Recycle"
        }
      ],
      "master_servers": [
        {
          "fqdn": "oc01.some.domain.net",
          "ipaddress": "172.21.65.131"
        },
        {
          "fqdn": "oc02.some.domain.net",
          "ipaddress": "172.21.65.132"
        },
        {
          "fqdn": "oc03.some.domain.net",
          "ipaddress": "172.21.65.133"
        }
      ],
      "etcd_servers": [
        {
          "fqdn": "oc01.some.domain.net",
          "ipaddress": "172.21.65.131"
        },
        {
          "fqdn": "oc02.some.domain.net",
          "ipaddress": "172.21.65.132"
        },
        {
          "fqdn": "oc03.some.domain.net",
          "ipaddress": "172.21.65.133"
        }
      ],
      "node_servers": [
        {
          "fqdn": "oc04.some.domain.net",
          "ipaddress": "172.21.65.134",
          "labels": "region=infra"
        },
        {
          "fqdn": "oc05.some.domain.net",
          "ipaddress": "172.21.65.135",
          "labels": "region=infra"
        }
      ]
    }
  }

```

Could you please help, how can i aproach to this error ?

**Comment by jperville** [comment] 2017-05-17 07:39
Hello @ebenezar-mccoy , you seem to be using openshift v1.5.0.

We are still working on supporting that version (see today's commits on master) but the official release is not cut yet.

You can either try the github master version of this cookbook, or stick to openshift origin v1.4.1 until the new release comes.

**Comment by ebenezar-mccoy** [comment] 2017-05-18 05:48
Thanks,

Switching back to 1.4.1 solves problem.
Fingers crossed for 1.5.0 release then :)

**Comment by IshentRas** [comment] 2017-05-18 05:54
@ebenezar-mccoy I can see where the issue is and it is going to be fixed ASAP.
Thanks for reporting :+1:

**Comment by jperville** [comment] 2017-05-19 08:31
Bug confirmed for v1.5.0, even with the latest github master. Working on it.

**Comment by IshentRas** [comment] 2017-05-21 17:25
@ebenezar-mccoy @jperville It has now been fixed with new release.
https://github.com/IshentRas/cookbook-openshift3/blob/master/CHANGELOG.md#v11048

**Closed by IshentRas** 2017-05-21 17:25 UTC
